### ISSUE TITLE
missing Features

### ISSUE THREAD

**Issue by Skyhighescaperoom** [playfultechnology/esp32-smartcube#1]
Hi Playful Tech,

Very nice work! i ordered the cube and the ESP32.
And like to use it in my escape room, but i missing a few things.
A status Led that the ESP32 and the cube are connected. (led on the ESP32 board)
The cube is hard to solve, we like to use it that the players only have to solve 1 side.
How can we enter that solve line? Like only RED side or Green side.
And we are missing a status of the batterij of the cube, so we can change batterij on time.
Maybe also a led on the ESP32 that wil light up when the batterij is getting low.

I really love your work! and watching all your video's.

I hope you can help me with the extra code. 
Because im not a programmer i use alot of node-red solutions.

Best regards,

Ivan Stupavski
Sky High Escape Room

**Comment by alastaira** [comment]
LED status is a good idea - I'll add that in a future version.

The decoded pData array in the notifyCallback function describes the current location and orientation of all the blocks as a series of half-bytes - first the corner pieces, then the edge pieces. The correct solved state is given at the top of the code: 0x12,0x34,0x56,0x78,0x33,0x33,0x33,0x33,0x12,0x34,0x56,0x78,0x9a,0xbc,0x00,0x00 - but you could examine a subset of that to determine whether a single face is solved instead.
